name: GraphQL
on: [pull_request]
jobs:
  graphql-schema-genaration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
      - name: Generate GraphQL Schema
        run: |
          bundle exec rails graphql:schema:dump
      - name: Commit GraphQL Schema files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-Generate GraphQL Schema
  nextjs-repo-test:
    runs-on: ubuntu-latest
    needs: [graphql-schema-genaration]
    steps:
      - name: build and test next.js repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: konyu
          repo: graphql_next
          github_token: ${{ secrets.GRAPHTL_NEXT_TOKEN }}
          workflow_file_name: trigger.yml
          propagate_failure: true