name: GraphQL
on: [pull_request]
jobs:
  graphql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
      - name: Generate GraphQL Schema
        run: |
          bundle exec rails graphql:schema:dump
      - name: Commit GraphQL Schema files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-Generate GraphQL Schema
